const { describe, expect, test } = require("bun:test");
const fs = require("node:fs");
const path = require("node:path");

describe("workflow config", () => {
  test("ci runs the package validation scripts", () => {
    const workflow = readWorkflow("ci.yml");

    expect(workflow).toContain("run: bun run typecheck");
    expect(workflow).toContain("run: bun run test");
    expect(workflow).toContain("run: bun run pack");
  });

  test("release builds desktop artifacts and publishes npm packages from releases", () => {
    const workflow = readWorkflow("release.yml");

    expect(workflow).toContain("name: Prepare release");
    expect(workflow).toContain("branches:");
    expect(workflow).toContain("- main");
    expect(workflow).toContain("paths:");
    expect(workflow).toContain("- package.json");
    expect(workflow).toContain("- packages/opencode-agent-pets/package.json");
    expect(workflow).toContain("- packages/claude-code-agent-pets/package.json");
    expect(workflow).toContain("- packages/gemini-agent-pets/package.json");
    expect(workflow).toContain("- packages/cursor-agent-pets/package.json");
    expect(workflow).toContain("- packages/aider-agent-pets/package.json");
    expect(workflow).toContain("- packages/goose-agent-pets/package.json");
    expect(workflow).toContain("- packages/copilot-agent-pets/package.json");
    expect(workflow).toContain("- packages/windsurf-agent-pets/package.json");
    expect(workflow).toContain("- packages/cline-agent-pets/package.json");
    expect(workflow).toContain("- packages/continue-agent-pets/package.json");
    expect(workflow).toContain("- packages/zed-agent-pets/package.json");
    expect(workflow).toContain("- packages/warp-agent-pets/package.json");
    expect(workflow).toContain('elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then');
    expect(workflow).toContain("git show HEAD^:package.json > /tmp/previous-package.json");
    expect(workflow).toContain("git show HEAD^:packages/opencode-agent-pets/package.json > /tmp/previous-opencode-package.json");
    expect(workflow).toContain("git show HEAD^:packages/claude-code-agent-pets/package.json > /tmp/previous-claude-code-package.json");
    expect(workflow).toContain("git show HEAD^:packages/gemini-agent-pets/package.json > /tmp/previous-gemini-package.json");
    expect(workflow).toContain("git show HEAD^:packages/cursor-agent-pets/package.json > /tmp/previous-cursor-package.json");
    expect(workflow).toContain("git show HEAD^:packages/aider-agent-pets/package.json > /tmp/previous-aider-package.json");
    expect(workflow).toContain("git show HEAD^:packages/goose-agent-pets/package.json > /tmp/previous-goose-package.json");
    expect(workflow).toContain("git show HEAD^:packages/copilot-agent-pets/package.json > /tmp/previous-copilot-package.json");
    expect(workflow).toContain("git show HEAD^:packages/windsurf-agent-pets/package.json > /tmp/previous-windsurf-package.json");
    expect(workflow).toContain("git show HEAD^:packages/cline-agent-pets/package.json > /tmp/previous-cline-package.json");
    expect(workflow).toContain("git show HEAD^:packages/continue-agent-pets/package.json > /tmp/previous-continue-package.json");
    expect(workflow).toContain("git show HEAD^:packages/zed-agent-pets/package.json > /tmp/previous-zed-package.json");
    expect(workflow).toContain("git show HEAD^:packages/warp-agent-pets/package.json > /tmp/previous-warp-package.json");
    expect(workflow).toContain('if [ "${version}" != "${previous_version}" ] || [ "${opencode_version}" != "${previous_opencode_version}" ] || [ "${claude_code_version}" != "${previous_claude_code_version}" ] || [ "${gemini_version}" != "${previous_gemini_version}" ] || [ "${cursor_version}" != "${previous_cursor_version}" ] || [ "${aider_version}" != "${previous_aider_version}" ] || [ "${goose_version}" != "${previous_goose_version}" ] || [ "${copilot_version}" != "${previous_copilot_version}" ] || [ "${windsurf_version}" != "${previous_windsurf_version}" ] || [ "${cline_version}" != "${previous_cline_version}" ] || [ "${continue_version}" != "${previous_continue_version}" ] || [ "${zed_version}" != "${previous_zed_version}" ] || [ "${warp_version}" != "${previous_warp_version}" ]; then');
    expect(workflow).toContain("opencode_version=\"$(node -p \"require('./packages/opencode-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("claude_code_version=\"$(node -p \"require('./packages/claude-code-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("gemini_version=\"$(node -p \"require('./packages/gemini-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("cursor_version=\"$(node -p \"require('./packages/cursor-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("aider_version=\"$(node -p \"require('./packages/aider-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("goose_version=\"$(node -p \"require('./packages/goose-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("copilot_version=\"$(node -p \"require('./packages/copilot-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("windsurf_version=\"$(node -p \"require('./packages/windsurf-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("cline_version=\"$(node -p \"require('./packages/cline-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("continue_version=\"$(node -p \"require('./packages/continue-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("zed_version=\"$(node -p \"require('./packages/zed-agent-pets/package.json').version\")\"");
    expect(workflow).toContain("warp_version=\"$(node -p \"require('./packages/warp-agent-pets/package.json').version\")\"");
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/opencode-agent-pets/package.json is ${opencode_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/claude-code-agent-pets/package.json is ${claude_code_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/gemini-agent-pets/package.json is ${gemini_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/cursor-agent-pets/package.json is ${cursor_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/aider-agent-pets/package.json is ${aider_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/goose-agent-pets/package.json is ${goose_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/copilot-agent-pets/package.json is ${copilot_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/windsurf-agent-pets/package.json is ${windsurf_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/cline-agent-pets/package.json is ${cline_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/continue-agent-pets/package.json is ${continue_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/zed-agent-pets/package.json is ${zed_version}.');
    expect(workflow).toContain('Version mismatch: package.json is ${version}, packages/warp-agent-pets/package.json is ${warp_version}.');
    expect(workflow).toContain('tag="v${version}"');
    expect(workflow).toContain('gh release view "${tag}"');
    expect(workflow).toContain('bun pm view "@ifbars/agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "opencode-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "claude-code-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "gemini-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "cursor-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "aider-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "goose-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "copilot-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "windsurf-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "cline-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "continue-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "zed-agent-pets@${version}" version');
    expect(workflow).toContain('bun pm view "warp-agent-pets@${version}" version');
    expect(workflow).toContain("release_exists: ${{ steps.release.outputs.release_exists }}");
    expect(workflow).toContain("gh release create");
    expect(workflow).toContain("find release-artifacts -type f -print0");
    expect(workflow).toContain('"${release_files[@]}"');
    expect(workflow).toContain("dist/*.exe");
    expect(workflow).not.toContain("dist/**/*.exe");
    expect(workflow).toContain('--target "${GITHUB_SHA}"');
    expect(workflow).toContain("name: Publish npm packages from GitHub release");
    expect(workflow).toContain("if: needs.prepare.outputs.should_release == 'true' && github.event_name == 'release'");
    expect(workflow).toContain("name: Publish npm packages from generated release");
    expect(workflow).toContain("needs.prepare.outputs.release_exists == 'true' || needs.github-release.result == 'success'");
    expect(workflow).toContain("continue-on-error: true");
    expect(workflow).toContain("name: Check npm publish results");
    expect(workflow).toContain("opencode-agent-pets publish failed.");
    expect(workflow).toContain("claude-code-agent-pets publish failed.");
    expect(workflow).toContain("gemini-agent-pets publish failed.");
    expect(workflow).toContain("cursor-agent-pets publish failed.");
    expect(workflow).toContain("aider-agent-pets publish failed.");
    expect(workflow).toContain("goose-agent-pets publish failed.");
    expect(workflow).toContain("copilot-agent-pets publish failed.");
    expect(workflow).toContain("windsurf-agent-pets publish failed.");
    expect(workflow).toContain("cline-agent-pets publish failed.");
    expect(workflow).toContain("continue-agent-pets publish failed.");
    expect(workflow).toContain("zed-agent-pets publish failed.");
    expect(workflow).toContain("warp-agent-pets publish failed.");
    expect(workflow).toContain("bun publish --access public");
    expect(workflow).toContain("working-directory: packages/opencode-agent-pets");
    expect(workflow).toContain("working-directory: packages/claude-code-agent-pets");
    expect(workflow).toContain("working-directory: packages/gemini-agent-pets");
    expect(workflow).toContain("working-directory: packages/cursor-agent-pets");
    expect(workflow).toContain("working-directory: packages/aider-agent-pets");
    expect(workflow).toContain("working-directory: packages/goose-agent-pets");
    expect(workflow).toContain("working-directory: packages/copilot-agent-pets");
    expect(workflow).toContain("working-directory: packages/windsurf-agent-pets");
    expect(workflow).toContain("working-directory: packages/cline-agent-pets");
    expect(workflow).toContain("working-directory: packages/continue-agent-pets");
    expect(workflow).toContain("working-directory: packages/zed-agent-pets");
    expect(workflow).toContain("working-directory: packages/warp-agent-pets");
    expect(workflow).toContain("NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}");
  });
});

function readWorkflow(name) {
  return fs.readFileSync(path.join(__dirname, "..", ".github", "workflows", name), "utf8");
}
